version: '3'

services:
  jupyter:
    image: jupyter/base-notebook
    container_name: jupyter
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
    user: root
    command: 'start-notebook.sh --NotebookApp.token='
